stages:
    - test
    - publish
    - pages

before_script:
    # ensure we have access to the npm registry
    - echo "registry=$NPM_REGISTRY" >> .npmrc
    - echo "_auth=$NPM_AUTH_KEY" >> .npmrc

test:
    stage: test
    image: node:10.15.1-alpine
    except:
        - tags
    script:
        - npm ci
        - npm t

publish:
    stage: publish
    image: node:10.15.1-alpine
    only:
        - tags
    script:
        # clean install
        - npm ci
        # publish to npm
        - npm publish

pages:
    stage: pages
    image: node:10.15.1-alpine
    script:
        - npm ci
        - cd example && npm ci && npm run build
        - mv build ../public
    only:
        - master
    artifacts:
        paths:
            - public
